SimpleSAML_Error_Error: Remove unused $this->cause.
git-svn-id: https://simplesamlphp.googlecode.com/svn/trunk@2526 44740490-163a-0410-bde0-09ae8108e29a